### ISSUE TITLE
travis-ci grabs wrong boot image when testing branches

### ISSUE THREAD

**Issue by erg** [factor/factor#2005]
Example: https://travis-ci.org/factor/factor/jobs/393224542

It should grab the ``nipd`` boot image from ``http://downloads.factorcode.org/images/nipd/`` instead of the ``master`` boot image.

Is this because the ``.travis.yml`` file has the following?

```yaml
branches:
  only:
    - master
```
